### ISSUE TITLE
Can't use local ollama server

### ISSUE THREAD

**Issue by bussyjd** [HabermannR/Fantasy-Tribe-Game#1]
When trying to use a local ollama with llama3.2 I get the following error.

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/user/Fantasy-Tribe-Game/Fantasy-Tribe-Game.py", line 178, in make_api_call
    return response_model.model_validate_json(completion.choices[0].message.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Fantasy-Tribe-Game/venv/lib/python3.12/site-packages/pydantic/main.py", line 625, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for InitialChoices
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='```json\n{\n  "Tribe 1":...g wealth."\n  }\n}\n```', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/json_invalid
```

To reproduce:
- set: `self.model = "llama3.2"`
- set `local_url: str = "http://localhost:11434/v1"

**Comment by HabermannR** [comment]
It seems Ollama can output in Json, but not as a structured output, meaning is just chooses a json format, and cannot follow a given format.
Sorry, but I will keep my eyes open

**Comment by HabermannR** [comment]
I found this library:
https://github.com/instructor-ai/instructor
Its seems to work, will update tomorrow.

**Comment by HabermannR** [comment]
@bussyjd 
Hi, I did not get this to work at all, even with the instructor library.
But I did split the LLM into a hybrid system, a story LLM, which must have structured output, and a summary LLM, which can be used with normal output. See 26ca3f4840df7d6c98c2efdf120f7fe2c6fe994d 
So you could use ollama for the summary LLM, but still need an external LLM for the story mode.

**Comment by bussyjd** [comment]
Hi,
Thanks for adjusting.
For info this:
https://github.com/mangiucugna/json_repair
could be interesting to further sanitize and ensure JSON from LLMs
